language: node_js
node_js:
- '12'
env:
  global:
  # REGISTRY_TOKEN(editor=cozy, app=bipandgo)
  - secure: goa2CiPwuj8cNnQosFSldZ3V0XAMWib7cfEGLwyZJu9vOVuWck3JLOnbyugjqfXDamuo+Fdn6H5Jm/43qjvpWwX7tTEv487wJCnpNLDXhMa/QpoFV5nNFuq83e5MOii6ahGx8i54TSiCjRIMI2M/IH7HC3SoTObyEZ4sx+ELiwpnxNZhDAwbPNfiEi1vgARk+kap4DoV2nfzDyWfp1rj3JmTMzeZH9W4eEOS4mJHOOP1QiGA/40TaVWG/twUsGTew1WjNUuivHHcuLf7wzGGM+cMier3g22/j9f0qKKh6XYI4oWjigkNrwPHXAz2HuFqK1EGPwUu12TsNgb+LmJ3h6+//C2FoTJ5Evh+isMb3teVTix08QkzEIPbAUNKD4T8OOBgMnV0nawpatY/IJoiIz012c5fJoLZSWzw8oS1ifYoqQ9tlTLmRlic39bFmqLY1BsYgUqRERvaMoz4/z8OrSwuvlPlVgWHwi+xFCu/CyHBJWJHdegxrFEKeYxoxVaHCeRxsU+XV/9zsa5b61H+1RAL/V8sufbMmBJrIKAigrDhHxlXumm8ZECCrGMXQ9XP8P8KFEsO8Z9gfHswId0xo6XOEWRF2sbzXqXWqSwJwFsPzC2m7MsL/5+z8o0siofB3NWinDizpXK1KSHt1WEe1KY+jPkcTZxGPEd5p8HDWDo=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_c5859a3a95f8_key -iv $encrypted_c5859a3a95f8_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
